name: CI Pipeline for Dev Agent

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  PYTHON_VERSION: "3.10"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov httpx

      - name: Rename test.py if needed (avoid conflict)
        run: |
          if [ -f backend/test/test.py ]; then
            mv backend/test/test.py backend/test/test_app.py
          fi

      - name: Run tests
        run: |
          pytest backend/test/ --cov=backend --cov-report=xml -v

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: success()
        with:
          file: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}  # facultatif si repo public

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install linters
        run: |
          pip install black flake8 isort mypy

      - name: Run Black formatting check
        run: |
          black --check backend/

      - name: Run Flake8
        run: |
          flake8 backend/

      - name: Run isort
        run: |
          isort --check-only backend/

      - name: Run mypy
        run: |
          mypy backend/
