name: CI Pipeline for Dev Agent

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  PYTHON_VERSION: "3.10"

jobs:
  lint_and_test:
    name: Lint Code and Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install linters
        run: |
          pip install black flake8 isort mypy pytest

      - name: Run Black (auto format)
        run: |
          black backend/ --check || black backend/  # Auto format if check fails

      - name: Run Flake8
        run: |
          flake8 backend/

      - name: Run isort
        run: |
          isort backend/ --check-only

      - name: Run mypy
        run: |
          mypy backend/

      - name: Run Tests
        run: |
          pytest backend/test --maxfail=1 --disable-warnings -q
