name: CI Pipeline for Dev Agent

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  PYTHON_VERSION: "3.10"

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install linters
        run: |
          pip install black flake8 isort mypy

      - name: Run Black (auto format)
        run: |
          black backend/

      - name: Run Flake8
        run: |
          flake8 backend/

      - name: Run isort
        run: |
          isort backend/

      - name: Run mypy
        run: |
          mypy backend/
